### ISSUE TITLE
Error:A problem occurred configuring project ':app'. > executing external native build for ndkBuild 

### ISSUE THREAD

**Issue by sanribadu** [Lauszus/FaceRecognitionApp#3] opened 2017-03-08 00:46 UTC
Error:A problem occurred configuring project ':app'.
> executing external native build for ndkBuild /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/Android.mk

Error:(45) *** Android NDK: Aborting    .  Stop.

Hello getting the error above. Thank you

**Comment by Lauszus** [comment] 2017-03-08 11:12
@sanribadu I believe this is a duplicate of #1. Also please post the full error log.

**Comment by sanribadu** [comment] 2017-03-08 11:59
![screen shot 2017-03-08 at 12 52 29](https://cloud.githubusercontent.com/assets/24362219/23703092/8027cf7a-03fe-11e7-8bae-1a31e87a7522.png)

And i am not sure if this is correct: setting the path of the openc cv and the eigen
```Make
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

OPENCV_INSTALL_MODULES := on

OPENCVROOT:= /Users/suleimanribadusani/Documents/OpenCV-2.4.9-android-sdk
include ${OPENCVROOT}/sdk/native/jni/OpenCV.mk

EIGEN3_DIR:= /Users/suleimanribadusani/Documents/eigen-eigen-26667be4f70b


LOCAL_MODULE := face-lib
LOCAL_SRC_FILES += $(LOCAL_PATH)/face-lib.cpp $(LOCAL_PATH)/FaceRecognitionLib/Facebase.cpp
LOCAL_SRC_FILES += $(LOCAL_PATH)/FaceRecognitionLib/Eigenfaces.cpp $(LOCAL_PATH)/FaceRecognitionLib/Fisherfaces.cpp
LOCAL_SRC_FILES += $(LOCAL_PATH)/FaceRecognitionLib/PCA.cpp $(LOCAL_PATH)/FaceRecognitionLib/LDA.cpp
LOCAL_C_INCLUDES += $(EIGEN3_DIR) $(LOCAL_PATH)/FaceRecognitionLib/RedSVD/include
LOCAL_LDLIBS += -llog -ldl
LOCAL_CPPFLAGS += -std=gnu++11 -frtti -fexceptions

include $(BUILD_SHARED_LIBRARY)
```

**Comment by Lauszus** [comment] 2017-03-08 15:16
@sanribadu you are using OpenCV 2.4.9 Please update to 3.1.0: <https://github.com/opencv/opencv/releases/download/3.1.0/OpenCV-3.1.0-android-sdk.zip>.

**Comment by sanribadu** [comment] 2017-03-08 16:10
Updated to 3.1.0 and the still getting the "executing external native build for ndkBuild .. Error :"
 
![screen shot 2017-03-08 at 17 09 51](https://cloud.githubusercontent.com/assets/24362219/23712082/0bee78d8-0422-11e7-9922-83f24b813082.png)


Could it be because i did not use the set environment variable approach?

**Comment by Lauszus** [comment] 2017-03-08 22:53
Have you installed Android NDK for Android studio? Can you see the full Gradle log somewhere, so I can see the full error message?

Btw I reopened the issue, as I believe you closed it by accident?

**Comment by sanribadu** [comment] 2017-03-08 22:56
yes installed the android NDk... and here is the log:

```
External Native Build Issues
Build command failed.
Error while executing '/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/ndk-build' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/Android.mk NDK_APPLICATION_MK=/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDEBUG=1 APP_PLATFORM=android-15 NDK_OUT=/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib NDK_DEBUG=1 NDEBUG=null APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
rm -f /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a/*
rm -f /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a/gdbserver
rm -f /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a/gdb.setup
mkdir -p /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a
echo [armeabi-v7a] "Gdbserver      ": "[arm-linux-androideabi] /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a/gdbserver"
install -p /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/prebuilt/android-arm/gdbserver/gdbserver /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a/gdbserver
echo [armeabi-v7a] "Gdbsetup       ": "/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a/gdb.setup"
echo "set solib-search-path /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a" > /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a/gdb.setup
echo "directory /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/platforms/android-15/arch-arm/usr/include "/Users/suleimanribadusani/Documents/OpenCV-android-sdk/sdk/native/jni/include/opencv" "/Users/suleimanribadusani/Documents/OpenCV-android-sdk/sdk/native/jni/include" /Users/suleimanribadusani/Documents/eigen-eigen-26667be4f70b /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/RedSVD/include /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward" >> /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/lib/armeabi-v7a/gdb.setup
mkdir -p /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/face-lib//Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp
echo [armeabi-v7a] "Compile++ thumb": "face-lib <= face-lib.cpp"
/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -MMD -MP -MF /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/face-lib//Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/face-lib.o.d -gcc-toolchain /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-exceptions -fno-rtti -mthumb -O0 -UNDEBUG -fno-limit-debug-info  -I"/Users/suleimanribadusani/Documents/OpenCV-android-sdk/sdk/native/jni/include/opencv" -I"/Users/suleimanribadusani/Documents/OpenCV-android-sdk/sdk/native/jni/include" -I/Users/suleimanribadusani/Documents/eigen-eigen-26667be4f70b -I/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/RedSVD/include -I/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -I/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -I/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp -DANDROID -fPIC -DANDROID -fsigned-char -Wa,--noexecstack -Wformat -Werror=format-security -std=gnu++11 -frtti -fexceptions   -std=gnu++11 -frtti -fexceptions  -isystem /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/platforms/android-15/arch-arm/usr/include -c  /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/face-lib.cpp -o /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/face-lib//Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/face-lib.o 
make: *** No rule to make target `/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.cpp', needed by `/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/face-lib//Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o'.  Stop.
Error:executing external native build for ndkBuild /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/Android.mk
Build command failed.
Error while executing '/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/ndk-build' with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/Android.mk NDK_APPLICATION_MK=/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDEBUG=0 APP_PLATFORM=android-15 NDK_OUT=/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -n}
rm -f /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/lib/armeabi-v7a/*
rm -f /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/lib/armeabi-v7a/gdbserver
rm -f /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/lib/armeabi-v7a/gdb.setup
mkdir -p /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/face-lib//Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp
echo [armeabi-v7a] "Compile++ thumb": "face-lib <= face-lib.cpp"
/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -MMD -MP -MF /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/face-lib//Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/face-lib.o.d -gcc-toolchain /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -g -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-exceptions -fno-rtti -mthumb -Os -DNDEBUG  -I"/Users/suleimanribadusani/Documents/OpenCV-android-sdk/sdk/native/jni/include/opencv" -I"/Users/suleimanribadusani/Documents/OpenCV-android-sdk/sdk/native/jni/include" -I/Users/suleimanribadusani/Documents/eigen-eigen-26667be4f70b -I/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/RedSVD/include -I/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -I/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -I/Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -I/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp -DANDROID -fPIC -DANDROID -fsigned-char -Wa,--noexecstack -Wformat -Werror=format-security -std=gnu++11 -frtti -fexceptions   -std=gnu++11 -frtti -fexceptions  -isystem /Users/suleimanribadusani/Library/Android/sdk/ndk-bundle/platforms/android-15/arch-arm/usr/include -c  /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/face-lib.cpp -o /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/face-lib//Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/face-lib.o 
make: *** No rule to make target `/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.cpp', needed by `/Users/suleimanribadusani/Documents/FaceRecognitionApp/app/build/intermediates/ndkBuild/release/obj/local/armeabi-v7a/objs/face-lib//Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/FaceRecognitionLib/Facebase.o'.  Stop.
Error:executing external native build for ndkBuild /Users/suleimanribadusani/Documents/FaceRecognitionApp/app/src/main/cpp/Android.mk
```

**Comment by Lauszus** [comment] 2017-03-09 11:48
You haven't checked out the submodule. Please run:
```bash
git submodule update --init --recursive
```

Also please check out the updates build instructions, so you can set the environmental variables instead of hardcoding the path: <https://github.com/Lauszus/FaceRecognitionApp#build-instructions>.

**Comment by Lauszus** [comment] 2017-03-14 00:24
@sanribadu any updates?

**Comment by sanribadu** [comment] 2017-03-16 23:12
sorry for the late reply been off for a while. Its not giving any error but the keeps saying that "E/JavaCameraView: Front camera not found!"

**Comment by Lauszus** [comment] 2017-03-17 01:02
What device are you using?

Try to replace this line: https://github.com/Lauszus/FaceRecognitionApp/blob/master/app/src/main/java/com/lauszus/facerecognitionapp/FaceRecognitionAppActivity.java#L369 with:

```Java
mOpenCvCameraView.setCameraIndex(prefs.getInt("mCameraIndex", CameraBridgeViewBase.CAMERA_ID_ANY));
```

**Comment by sanribadu** [comment] 2017-03-17 01:44
Thank you for the application, it is working fine now.

**Closed as completed** 2017-03-17 01:44 UTC

**Comment by Lauszus** [comment] 2017-03-17 11:30
You're welcome :)

**Comment by Lauszus** [comment] 2017-03-19 14:14
@sanribadu what device are you using? I guess there is no front camera on it?

**Comment by alike123** [comment] 2019-07-22 07:25
> 
> 
> You haven't checked out the submodule. Please run:
> 
> ```shell
> git submodule update --init --recursive
> ```
> 
> Also please check out the updates build instructions, so you can set the environmental variables instead of hardcoding the path: https://github.com/Lauszus/FaceRecognitionApp#build-instructions.
# git submodule update --init --recursive inwindows
Sorry to bother you. I'm working on windows. I have install the Git and add it to the environment variable. But when I run the command ,"git submodule update --init --recursive", in cmd, there are something wrong.

`$ git submodule update --init --recursive`
`fatal: E:/Program Files (x86)/Git/mingw64/libexec/git-core\git-submodule cannot
be used without a working tree.'`

**Comment by MustafaDar** [comment] 2019-11-29 07:08
sir i still didnt understand how the applicatin will recognize faces
Can you kindly help me with that?
